### ISSUE TITLE
Arceon ? Or FAWE issue ? or other...

### ISSUE THREAD

**Issue by Benjiiben53** [Brennian/Arceon-1.14#2]
Hello, I recently bought the Arceon Fawe 1.15+ plugins but when starting it it crashes.

`
[22:21:17 INFO]: [Arceon] Enabling Arceon v0.1.9_1.15+
[22:21:17 INFO]: [Arceon] Arceon loaded!
[22:21:17 ERROR]: Error occurred while enabling Arceon v0.1.9_1.15+ (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/MutableVector3
        at com.arceon.core.ArceonCommandManager.initialize(ArceonCommandManager.java:39) ~[?:?]
        at com.arceon.core.ArceonCommandManager.<init>(ArceonCommandManager.java:34) ~[?:?]
        at com.arceon.core.Main.onEnable(Main.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.MutableVector3
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more
[22:21:17 INFO]: [Arceon] Disabling Arceon v0.1.9_1.15+
`

Edit: The server is on purpur 1.16.5
I have try with the lasted version of FAWE, the lasted version of WorldEdit but nothing more When this error appear, i have this list of plugins:

Arceon,
BungeeTabListPlus,
Citizens, CoreProtect,
DisableJoinMessage*,
ExtraContexts*,
FastAsyncWorldEdit (WorldEdit),
FastChunkPregenerator,
GamemodeChanger*,
GameModeInventories,
GFly,
HolographicDisplays,
InvSeePlusPlus,
LuckPerms,
MultiChat*,
Multiverse-Core,
Multiverse-Portals,
NewbsCreative,
PlaceholderAPI,
PlotSquared,
ProtocolLib,
SetHomes,
SkinsRestorer,
TigerReports,
TigerReportsSupports*,
Vault,
ViaVersion,
VoidGen,
VoxelSniper,
WorldGuard

Thank in advance for helping and have a nice day !

PS: I'm on vacation for the next 4 days... sorry if I don't answer before

**Comment by Brennian** [comment]
This is fixed in the latest version

From: ***@***.***>
Sent: Monday, 26 July 2021 22:33
To: ***@***.***>
Cc: ***@***.***>
Subject: [Brennian/Arceon-1.14] Arceon ? Or FAWE issue ? or other... (#2)


Hello, I recently bought the Arceon Fawe 1.15+ plugins but when starting it it crashes.

[22:21:17 INFO]: [Arceon] Enabling Arceon v0.1.9_1.15+ [22:21:17 INFO]: [Arceon] Arceon loaded! [22:21:17 ERROR]: Error occurred while enabling Arceon v0.1.9_1.15+ (Is it up to date?) java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/MutableVector3 at com.arceon.core.ArceonCommandManager.initialize(ArceonCommandManager.java:39) ~[?:?] at com.arceon.core.ArceonCommandManager.<init>(ArceonCommandManager.java:34) ~[?:?] at com.arceon.core.Main.onEnable(Main.java:49) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.Thread.run(Thread.java:831) [?:?] Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.MutableVector3 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] ... 13 more [22:21:17 INFO]: [Arceon] Disabling Arceon v0.1.9_1.15+

I have try with the lasted version of FAWE, the lasted version of WorldEdit but nothing more When this error appear, i have this list of plugins:

Arceon,
BungeeTabListPlus,
Citizens, CoreProtect,
DisableJoinMessage*,
ExtraContexts*,
FastAsyncWorldEdit (WorldEdit),
FastChunkPregenerator,
GamemodeChanger*,
GameModeInventories,
GFly,
HolographicDisplays,
InvSeePlusPlus,
LuckPerms,
MultiChat*,
Multiverse-Core,
Multiverse-Portals,
NewbsCreative,
PlaceholderAPI,
PlotSquared,
ProtocolLib,
SetHomes,
SkinsRestorer,
TigerReports,
TigerReportsSupports*,
Vault,
ViaVersion,
VoidGen,
VoxelSniper,
WorldGuard

Thank in advance for helping and have a nice day !

PS: I'm on vacation for the next 4 days... sorry if I don't answer before
